# I keep forgetting the values, so now there's constants for them...

# ADVANCEMENT

ADVANCEMENT = 0
ADVANCEMENT_HARD = 1
ADVANCEMENT_EXPLORATION = 2
ADVANCEMENT_UNREASONABLE = 3

# ITEMSANITY

ITEMSANITY = 5
ITEMSANITY_HARD = 6
ITEMSANITY_EXPLORATION = 7
ITEMSANITY_UNREASONABLE = 8

# OTHER ITEMSANITY

DISCS = 9
RARE_ORE = 10
MOB_HEADS = 11
NETHERITE = 12
TRIM = 13
SHERD = 14
DYE = 15
DYE_AND_EXPLORATION = 16

FLOWER = 17
FLOWER_AND_EXPLORATION = 18
FLOWER_AND_HARD = 19

SLAB = 20
SLAB_AND_EXPLORATION = 21

STAIR = 22
STAIR_AND_EXPLORATION = 23

WALL = 24
WALL_AND_EXPLORATION = 25