# Vanilla Minecraft Locations
create_advancements = [
    "Sturdier Rocks",
    "The Andesite Age",
    "Blacksmith Artillery",
    "Combust-o-Tron",
    "Organize-o-Tron",
    "Pressure to Go",
    "Kelp Drive",
    "The Parrots and the Flaps",
    "Real Alloys",
    "The Brass Age",
    "Sentient Fireplace",
    "Part and Parcel",
    "Full Stealth",
    "Arts and Crafts",
    "Strong Arms",
    "On a Roll",
    "A World of Imagination",
    "Vertical Logistics",
    "Contraption o'Clock",
    "Compactification",
    "Conductor Instructor",
    "Moving with Purpose",
    "Cuprum Bokum",
    "The Copper Age",
    "Desperate Measures",
    "Don't Cross the Streams!",
    "Crushing It",
    "Wheels of Destruction",
    "Is it Time?",
    "Artificial Intelligence",
    "Dynamic Timetables",
    "Big Data",
    "Ready for the Depths",
    "Swimming with the Striders",
    "Tumble Draining",
    "Springboard Champion",
    "Wind Maker",
    "Boioioing!",
    "To Full Extent",
    "High Logistics",
    "Processing by Particle",
    "Pound It, Bro!",
    "Balanced Diet (Create)",
    "Hungry hoppers",
    "Airport Aesthetic",
    "Flow Discovery",
    "Workout Session",
    "Shadow Sense",
    "Autonomous Bee-Keeping",
    "Industrial Spillage",
    "Tapping the Mantle",
    "Magma Wheel",
    "Remote Activation",
    "Ambitious Endeavours",
    "Field Trip",
    "Busy Hands",
    "Automated Assembly",
    "Mixing It Up",
    "Bonk!",
    "Under Pressure",
    "Embrace the Grind",
    "DJ Mechanico",
    "Nothing but net",
    "Post Production",
    "The Pipe Organ",
    "Drive-by Exchange",
    "Fwoomp!",
    "Veggie Fireworks",
    "Complex Curiosities",
    "Rope to Nowhere",
    "Expert Driver",
    "Supercharged",
    "Workshop's Most Feared",
    "Self-Driving Cart",
    "Shifting Gears",
    "Engineers hate this simple trick!",
    "Sploosh",
    "The Powerhouse",
    "Full Steam",
    "Voice of an Angel",
    "Order Up!",
    "Stress for Nerds",
    "Perfectly Stressed",
    "The Sturdiest Rocks",
    "Area of Connect",
    "Open for business",
    "A New Gauge",
    "Track Factory",
    "Traffic Control",
    "All Aboard!",
    "The Locomotive Age",
    "Terrible Service",
    "Blind Spot",
    "Dimensional Commuter",
    "Road Kill",
    "Choo Choo!",
    "Harnessed Hydraulics",
    "A mild Breeze",
    "A strong Breeze",
    "Kitted Out"
]